services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8081:${API_PORT}"
    depends_on:
      - database
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "3000:${WEB_PORT}"
    depends_on:
      - api
    env_file:
      - .env

  database:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "5432:${POSTGRES_PORT}"
    env_file:
      - .env