services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "3000:${WEB_PORT}"
    depends_on:
      - api
    env_file:
      - .env