services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8081:${API_PORT}"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl", "localhost:${API_PORT}/appinfo"]
      interval: 10s
      retries: 3
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "3000:${WEB_PORT}"
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - .env

  database:
    image: postgres:${POSTGRES_VERSION}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 3
    ports:
      - "5432:${POSTGRES_PORT}"
    env_file:
      - .env